# Generated by Django 5.2.15 on 2026-06-22 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import orm.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "token",
                    models.CharField(
                        default=orm.models._new_token,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionSession",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=orm.models._new_session_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("test_env", models.BooleanField(default=True)),
                ("state", models.JSONField(blank=True, null=True)),
                ("state_saved_at", models.DateTimeField(blank=True, null=True)),
                ("dh_export_sample", models.JSONField(blank=True, null=True)),
                (
                    "dh_export_sample_saved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("dh_export_experiment", models.JSONField(blank=True, null=True)),
                (
                    "dh_export_experiment_saved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reads_log", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadsRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_name", models.CharField(max_length=255)),
                ("stable_alias", models.CharField(max_length=512)),
                ("status", models.CharField(max_length=32)),
                (
                    "experiment_accession",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "run_accession",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "submitted_alias",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads_runs",
                        to="orm.submissionsession",
                    ),
                ),
            ],
            options={
                "ordering": ["run_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="submissionsession",
            constraint=models.UniqueConstraint(fields=("owner", "name"), name="uniq_session_name_per_owner"),
        ),
        migrations.AddConstraint(
            model_name="readsrun",
            constraint=models.UniqueConstraint(fields=("session", "run_name"), name="uniq_run_per_session"),
        ),
    ]
